### PR TITLE
Fix incorrect object key in call to getTotalCount

### LINKED ISSUE #8: TypeError: Cannot read property 'model' of undefined
When trying to use ConnectionFromMongoCursor I'm getting the error:

`TypeError: Cannot read property 'model' of undefined ...  graphql-mongoose-loader/lib/ConnectionFromMongoCursor.js:53:34`

Or this line:

`clonedCursor = cursor.model.find().merge(cursor);`

I've tried debugging and believe it's to do with the `getTotalCount` call but since this is async wrapped in the regeneratorRuntime its proving difficult. Is this a problem for anyone else?

Thank you.

### PR DESCRIPTION
**Pull request by davidrossjones**
The function getTotalCount accepts a `cursor` key and not `clonedCursor`. Fixes #8.

### CODE REVIEW

File: src/ConnectionFromMongoCursor.js [hunk 1]
```diff
@@ -149,7 +149,7 @@ const connectionFromMongoCursor = async ({
   const clonedCursor = cursor.model.find().merge(cursor);
 
   const totalCount = await getTotalCount({
-    clonedCursor,
+    cursor: clonedCursor,
```
Comment (sibelius) [inline src/ConnectionFromMongoCursor.js]: nice
